export const strings = {
  // Auth Screens
  auth: {
    login: {
      title: 'Welcome back',
      subtitle: 'Sign in to your account',
      emailPlaceholder: 'Email',
      passwordPlaceholder: 'Password',
      forgotPassword: 'Forgot password?',
      signIn: 'Sign In',
      noAccount: 'Don\'t have an account?',
      signUp: 'Sign Up',
      errors: {
        emailRequired: 'Email is required',
        emailInvalid: 'Email is invalid',
        passwordRequired: 'Password is required',
        passwordTooShort: 'Password must be at least 6 characters',
        invalidCredentials: 'Invalid email or password',
      },
    },
    signUp: {
      title: 'Create Account',
      subtitle: 'Sign up to get started',
      namePlaceholder: 'Full Name',
      emailPlaceholder: 'Email',
      passwordPlaceholder: 'Password',
      confirmPasswordPlaceholder: 'Confirm Password',
      createAccount: 'Create Account',
      haveAccount: 'Already have an account?',
      signIn: 'Sign In',
      errors: {
        nameRequired: 'Name is required',
        emailRequired: 'Email is required',
        emailInvalid: 'Email is invalid',
        passwordRequired: 'Password is required',
        passwordTooShort: 'Password must be at least 6 characters',
        passwordsDontMatch: 'Passwords don\'t match',
        emailInUse: 'Email is already in use',
      },
    },
    forgotPassword: {
      title: 'Forgot Password',
      subtitle: 'We\'ll send you a link to reset your password',
      emailPlaceholder: 'Email',
      resetPassword: 'Reset Password',
      backToLogin: 'Back to Login',
      emailSent: 'Reset link sent to your email',
      errors: {
        emailRequired: 'Email is required',
        emailInvalid: 'Email is invalid',
        emailNotFound: 'No account found with this email',
      },
    },
  },

  // Main App Screens
  app: {
    home: {
      title: 'Home',
      welcome: 'Welcome, ',
      recentActivity: 'Recent Activity',
      noActivity: 'No recent activity',
      quickActions: 'Quick Actions',
    },
    profile: {
      title: 'Profile',
      editProfile: 'Edit Profile',
      name: 'Name',
      email: 'Email',
      bio: 'Bio',
      save: 'Save Changes',
      photoChange: 'Change Photo',
      photoRemove: 'Remove Photo',
      accountInfo: 'Account Information',
      memberSince: 'Member Since',
      notifications: 'Notifications',
    },
    settings: {
      title: 'Settings',
      account: 'Account',
      preferences: 'Preferences',
      theme: 'Theme',
      language: 'Language',
      notifications: 'Notifications',
      about: 'About',
      logout: 'Logout',
      appearance: {
        title: 'Appearance',
        system: 'System Default',
        light: 'Light',
        dark: 'Dark',
      },
      languages: {
        title: 'Language',
        english: 'English',
        spanish: 'Spanish',
        french: 'French',
        german: 'German',
        japanese: 'Japanese',
      },
    },
    actions: {
      title: 'Actions',
      newAction: 'New Action',
      recentActions: 'Recent Actions',
      noActions: 'No recent actions',
    },
  },

  // Common UI elements
  common: {
    cancel: 'Cancel',
    save: 'Save',
    delete: 'Delete',
    edit: 'Edit',
    done: 'Done',
    loading: 'Loading...',
    error: 'An error occurred',
    retry: 'Retry',
    confirm: 'Confirm',
    next: 'Next',
    back: 'Back',
    search: 'Search',
    submit: 'Submit',
    success: 'Success!',
  },
};

export default strings;